name: CI

on:
  push:


jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Установить uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9
      - name: Установить зависимости
        run: uv sync
      - name: Проверка линтера
        run: uv run ruff check .
      - name: Запуск тестов
        run: uv run pytest
        env:
          GREETING: "CI"
          DATABASE_URL: "postgresql://ci:ci@db:5432/ci"
  publish:
    needs: check
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v7
      - name: Настроить сборщик Docker
        uses: docker/setup-buildx-action@4
      - name: Вход в реестр GHCR
        uses: docker/login-action@4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Сборка и публикация
        uses: Docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest